language: node_js
node_js:
  - 16
before_install:
  - npm install --global lerna
  - lerna bootstrap
script:
  - lerna run --parallel --stream start & wait-on http://localhost:8080
  - cd packages/editor-app
  - npx cypress run --record --key $CYPRESS_KEY
