# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Cypress Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install Lerna
      run: npm install --global lerna
        
    - name: Bootstrap
      run: lerna bootstrap

    - name: Run
      run: lerna run --parallel --stream start & wait-on http://localhost:8080
      
    - name: Test Editor
      run: cd packages/editor-app
    - run: pwd
    - run: npx cypress run
      
